services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: your_password
      MARIADB_DATABASE: kr_juso
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./202507_juso/utf8:/data/utf8 # 여기 마운트 추가
      - ./initdb:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mysql-files:/var/lib/mysql-files # (옵션) secure-file-priv에 파일 넣을 때 사용
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-pyour_password",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data:
